version: '3.8'

services:
  nestapp:
    build: ./
    container_name: nest-back-docker
    ports:
      - '3001:3000'
    env_file:
      - .env.development
    depends_on:
      - postgresdb
    networks:
      - nestnetwork
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  postgresdb:
    image: postgres:latest
    container_name: postgresdb2
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env.development
    networks:
      - nestnetwork
    environment:
      - TZ=America/Argentina/Buenos_Aires

networks:
  nestnetwork:
    driver: bridge

volumes:
  pgdata:
