version: '3.8'

services:
  nestapp:
    build: ./
    container_name: nest-back-docker
    ports:
      - '3001:3000'
    env_file:
      - .env.development
    depends_on:
      - postgresdb
    networks:
      - nestnetwork

  postgresdb:
    image: postgres:latest
    container_name: postgresdb2
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - nestnetwork

networks:
  nestnetwork:
    driver: bridge

volumes:
  pgdata:
